replicaCount: 1
image:
  repository: chartmuseum/chartmuseum
  tag: v0.2.5
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi

# Currently storage can be one of: [local, amazon]
storage: local

amazon:
  access_key:
  secret_key:
  region: us-east-1
  bucket:
  prefix:
  endpoint: