{{- if eq .Values.storage "amazon" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-amazon
  labels:
{{ include "common.labels.standard" . | indent 4 }}
type: Opaque
data:
  access_key: {{ required "You must provide an Amazon Access Key." .Values.amazon.access_key | b64enc | quote }}
  secret_key: {{ required "You must provide an Amazon Secret Key." .Values.amazon.secret_key | b64enc | quote }}
{{- end -}}