apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      volumes:
      - name: storage-volume
        emptyDir: {}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: STORAGE
          value: {{ .Values.storage }}
        {{- if eq .Values.storage "local" }}
        - name: STORAGE_LOCAL_ROOTDIR
          value: /storage
        {{- end }}
        - name: PORT
          value: "{{ .Values.service.internalPort }}"
        - name: DEBUG
          value: "true"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /index.yaml
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /index.yaml
            port: {{ .Values.service.internalPort }}
        {{- if eq .Values.storage "local" }}
        volumeMounts:
        - mountPath: /storage
          name: storage-volume
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
